# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: organization

deployType: "PROD"
appProtocol: https
appDomain: localhost:7000

imageKey:
  registry: ghcr.io/gbdi
  repository: organization
  tag: 1
  secretName: ''

db:
  appName: database
  serviceName: database-service
  databaseName: organization
  configmap: db-config
  replicas: 1
  dockerImageTag: 7
  port: 27017
  secret:
    name: database-secret
    provider: ''
    providerNamespace: ''
    passwordValue: 'YWRnYWtqMjM1NGpoc2tsaDc4MzU0'
    usernameValue: 'cG9zdGdyZXN1c2Vy'

backend:
  appName: backend
  serviceName: backend-service
  configmap: backend-config
  replicas: 1
  servicePort: 8000
  secretName: backend-secret
  authApiKey: ""
  authConnectionUri: ""
  routerUrl: "http://localhost:7000/graphql"


