{{- if eq .Values.deployType "DEV" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.passwordSecret.name }}
  namespace: {{ .Values.namespace }}
type: generic
data:
  password: {{ .Values.db.passwordSecret.value }}
  username: {{ .Values.db.usernameSecret.value }}
{{- else if eq .Values.deployType "PROD"}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: {{ .Values.db.secret.name }}
  namespace: default
spec:
  appName: {{ .Values.db.appName }}
  destination:
    create: true
    labels:
      hvs: "true"
    name: {{ .Values.db.secret.name }}
  refreshAfter: 1h
{{- end }}