namespace: router
appName: router
appDomain: 'api.gbdi.io'
tlsSecret: 'api-gbdi-io'
serviceName: router-service
servicePort: 7000
replicas: 1
secretName: router-secrets
deployType: 'PROD'

imageKey:
  registry: ghcr.io/gbdi
  repository: rover
  tag: 1

router:
  imageTag: v1.53.0
  logLevel: info

clientOrigin: 'http://localhost:8000'
authUrl: 'http://localhost:7001'
organizationUrl: 'http://localhost:7002'
projectsUrl: 'http://localhost:7003'
