federation_version: =2.3.2
subgraphs:
#  organization:
#    routing_url: "http://localhost:7002/api/graphql"
#    schema:
#      file: /app/schemas/organization.graphql
  projects:
    routing_url: "http://localhost:7003/api/graphql"
    schema:
      file: /app/schemas/projects.graphql

