federation_version: =2.8.0
subgraphs:
  auth:
    routing_url: "http://localhost:7001/api/graphql"
    schema:
      file: /app/schemas/auth.graphql
  organization:
    routing_url: "http://localhost:7002/api/graphql"
    schema:
      file: /app/schemas/organization.graphql
  projects:
    routing_url: "http://localhost:7003/api/graphql"
    schema:
      file: /app/schemas/projects.graphql

