apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.db.configmap }}
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_HOST: "{{ .Values.db.serviceName }}"
  POSTGRES_DB: "{{ .Values.db.databaseName }}"
  POSTGRES_PORT: "{{ .Values.db.port }}"
  POSTGRES_SSL: "{{ .Values.db.ssl }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.configmap }}
  namespace: {{ .Values.namespace }}
data:
  BACKEND_CORS_ORIGINS: "{{ .Values.appProtocol}}://{{ .Values.appDomain }}"
