{{- if eq .Values.deployType "DEV" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.passwordSecret.name }}
  namespace: {{ .Values.namespace }}
type: generic
data:
  password: {{ .Values.db.passwordSecret.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.usernameSecret.name }}
  namespace: {{ .Values.namespace }}
type: generic
data:
  username: {{ .Values.db.usernameSecret.value }}
{{- end }}