"""empty message

Revision ID: da1b2c036e80
Revises: 36d45956fe33
Create Date: 2025-09-24 17:52:24.347153

"""

import json
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.ext.asyncio import create_async_engine

from core.config import settings
from models.user import UserMetadata

# revision identifiers, used by Alembic.
revision: str = "da1b2c036e80"
down_revision: Union[str, Sequence[str], None] = "36d45956fe33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


async def migrate_supertokens_metadata(connection):
    postgres_supertokens_uri = f"postgresql+asyncpg://{settings.POSTGRES_USER}:{settings.POSTGRES_PASSWORD}@{settings.POSTGRES_HOST}:{settings.POSTGRES_PORT}/auth"
    connectable = create_async_engine(postgres_supertokens_uri, echo=True, future=True)

    async with connectable.connect() as _connection:
        # Try to query the old user_metadata table in SuperTokens schema
        # If it doesn't exist (fresh install), return empty list
        try:
            # result = await _connection.execute(sa.text("SELECT * FROM supertokens.user_metadata"))
            result = await _connection.execute(sa.text("SELECT * FROM user_metadata"))
            rows = result.fetchall()
            return rows
        except sa.exc.ProgrammingError:
            # Table doesn't exist (fresh install), nothing to migrate
            return []
        finally:
            await connectable.dispose()


def upgrade() -> None:
    """Upgrade schema."""

    rows = op.run_async(async_function=migrate_supertokens_metadata)
    if rows:  # Only insert if there's data to migrate
        op.bulk_insert(
            UserMetadata.__table__, [{"id": row.user_id, "meta_data": json.loads(row.user_metadata)} for row in rows]
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
