apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.db.configmap }}
  namespace: {{ .Values.namespace }}
data:
  DATABASE_HOST: "{{ .Values.db.serviceName }}"
  DATABASE_NAME: "{{ .Values.db.databaseName }}"
  DATABASE_PORT: "{{ .Values.db.port }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.configmap }}
  namespace: {{ .Values.namespace }}
data:
  SERVER_NAME: {{- template "serverName" }}
  SERVER_HOST: "http://localhost"
  BACKEND_CORS_ORIGINS: '["{{ .Values.appProtocol}}://{{ .Values.appDomain }}"]'
