# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: auth

deployType: "PROD"
appProtocol: https
appDomain: localhost:7000

imageKey:
  registry: gbdi
  repository: auth
  tag: 1

db:
  appName: database
  serviceName: database-service
  databaseName: auth
  configmap: db-config
  replicas: 1
  dockerImageTag: 13.1-alpine
  port: 5432
  secret:
    name: postgres-secret
    passwordValue: 'YWRnYWtqMjM1NGpoc2tsaDc4MzU0'
    usernameValue: 'cG9zdGdyZXN1c2Vy'

  ssl: false

backend:
  appName: backend
  serviceName: backend-service
  configmap: backend-config
  replicas: 1
  servicePort: 8000
  secretName: backend-secret
  serverName: auth
  serverHost: ""
  apiKey: ""
  connectionUri: ""


