# https://github.com/EPFL-ENAC/epfl-enac-build-push-deploy-action#readme
name: deploy

"on":
  push:
    branches:
      - dev
    tags: ['v*.*.*']

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: EPFL-ENAC/epfl-enac-build-push-deploy-action/.github/workflows/deploy.yml@v2.5.0
    secrets:
      token: ${{ secrets.CD_TOKEN }}
    with:
      org: gbdi
      repo: app
      build_context: '["./modules/auth", "./modules/organization", "./modules/projects", "./modules/router"]'
