name: Organization Module Workflow

on:
  push:
    branches:
      - main
    paths:
      - modules/organization/**
      - .github/workflows/**.yaml
  pull_request:
    branches:
      - main
    paths:
      - modules/organization/**
      - .github/workflows/**.yaml

  workflow_dispatch:


permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  test:
    uses: ./.github/workflows/run_tests.yaml
    with:
      working-directory: modules/organization/

#  publish-graphql:
#    uses: ./.github/workflows/publish_graphql.yaml
#    if: github.event_name != 'pull_request'
#    needs: test
#    with:
#      module-name: 'organization'
#      bucket-name: 'graphql'
#      branch: "${{ github.ref_name }}"
#      aws-region: ${{ vars.AWS_REGION }}
#    secrets:
#      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-container:
    uses: ./.github/workflows/publish_image.yaml
    needs: test
    with:
      tag: "${{ github.run_number }}${{ (github.ref_name != 'main' && '-dev') || ''}}"
      registry: "globalbuildingdatainitiative"
      name: 'organization'

  publish-chart:
    uses: ./.github/workflows/publish_chart.yaml
    needs:
      - test
      - build-container
    with:
      tag: "${{ github.run_number }}${{ (github.ref_name != 'main' && '-dev') || ''}}"
      registry: "globalbuildingdatainitiative"
      name: 'organization'