name: Project Module Workflow

on:
  push:
    branches:
      - main
      - stage
    paths:
      - modules/projects/**
      - .github/workflows/**.yaml
  pull_request:
    branches:
      - main
      - stage
    paths:
      - modules/projects/**
      - .github/workflows/**.yaml

  workflow_dispatch:


permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  test:
    uses: ./.github/workflows/run_tests.yaml
    with:
      working-directory: modules/projects/

  build-container:
    uses: ./.github/workflows/publish_image.yaml
    needs: test
    with:
      registry: "globalbuildingdatainitiative"
      name: 'projects'

  publish-chart:
    uses: ./.github/workflows/publish_chart.yaml
    needs:
      - test
      - build-container
    with:
      registry: "globalbuildingdatainitiative"
      name: 'projects'