name: Publish GraphQL Schema

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string
      bucket-name:
        required: true
        type: string
      branch:
        required: true
        type: string
      aws-region:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  publish-schema:
    name: Publish GraphQL Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ secrets.aws-region }}

      - name: Sync files to S3 bucket
        working-directory: modules/${{ inputs.module-name }}/graphql
        run: aws s3 cp schema.yaml s3://${{ inputs.bucket-name }}/graphql/${{ inputs.branch }}/${{ inputs.module-name}}