name: Build Container Image

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      name:
        required: true
        type: string

jobs:
  build-image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Log into registry ${{ inputs.registry }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        working-directory: modules/${{ inputs.name }}
        run: docker build -t ghcr.io/${{ inputs.registry }}/${{ inputs.name }}:${{ github.run_number }} .

      - name: Tag Image
        run: docker tag ghcr.io/${{ inputs.registry }}/${{ inputs.name }}:${{ github.run_number }} ghcr.io/${{ inputs.registry }}/${{ inputs.name }}:${{ github.ref_name }}

      - name: Push Image
        if: github.event_name != 'pull_request'
        working-directory: modules/${{ inputs.name }}
        run: docker push ghcr.io/${{ inputs.registry }}/${{ inputs.name }}:${{ github.run_number }} ghcr.io/${{ inputs.registry }}/${{ inputs.name }}:${{ github.ref_name }}